"""
This is a template run script for the solution file processing package. Do not edit this file, but copy it to the
main directory and edit it there.
"""

import solution_file_processing as sfp

# Initialize config with toml file
config = sfp.SolutionFilesConfig('config_files/ukraine/UKR2.toml')  # e.g. 'config_archive/vanilla_dev/IDN.toml'


sfp.plots.create_plot_1a_overall(config)
# sfp.plots.create_plot_2_summary(config)
# sfp.plots.create_plot_6_ldc_and_line_plots(config)