"""
This is a template run script for the solution file processing package. Do not edit this file, but copy it to the
main directory and edit it there.
"""

import solution_file_processing as sfp

# Initialize config with toml file
config = sfp.SolutionFilesConfig('config_files/ukraine/UKR2.toml')  # e.g. 'config_archive/vanilla_dev/IDN.toml'

# Only when running the first time
# config.install_dependencies()
config.convert_solution_files_to_h5()

# # # # Create plots (stored in output/plots)

sfp.plots.extract_plexos_LT_results(config, scale=1.05)
sfp.plots.create_plot_2_summary(config, plot_vars=config.QUICK_PLOTS, plot_name='quick')
