# The paths are based on the personal U: drive and will need to be changed for other users

[path]
model_dir = 'U:/data/Korea/Market design 2021'
soln_idx_path = 'U:/data/Korea/2022_07_22_generator_parameters_for_stochastic_2035_APS_cost_stochastic.xlsx'

[model]
soln_choice = '2023_06_02_main_reproc'

[settings]
geo_cols = ['Region', 'Subregion']
reg_ts = true

[run]
log_file_path = 'U:/code/solution-file-processing/logs/KOR.log'
log_timestamp = true
variables_cache = true
catch_errors = true

[testing]
baseline_output_dir = false # There is no baseline output directory for China, was created with older R code
similar_output_dirs = [
    'Y:/RED/Modelling/Indonesia/2021_IPSE/05_DataProcessing/20230509_IDN_APSvRUPTL_scenario/',
    'Y:/RED/Modelling/Thailand/2022-3_next_step_modelling/05_DataProcessing/20230626_THA_Base_LowerCO2p',
]
