# The paths are based on the personal U: drive and will need to be changed for other users

[path]
model_dir = 'U:/data/Thailand/2022-3_next_step_modelling'
soln_idx_path = 'U:/data/Thailand/2023_03_14_generator_parameters_THA.xlsx'

[model]
soln_choice = '20230626_THA_Base_LowerCO2p'

[settings]
geo_cols = ['Region', 'Subregion']
reg_ts = true

[run]
working_dir = 'U:/code/solution-file-processing'
log_file_path = 'U:/code/solution-file-processing/logs/THA.log'
log_timestamp = true
variables_cache = true
catch_errors = true

[testing]
baseline_output_dir = 'Y:/RED/Modelling/Thailand/2022-3_next_step_modelling/05_DataProcessing/20230626_THA_Base_LowerCO2p/'
similar_output_dirs = false
