[path]
model_dir = 'U:/Code/dev_dirs/Thailand/2022-3_next_step_modelling'
model_dir_test = 'Y:/RED/Modelling/Thailand/2022-3_next_step_modelling'
soln_idx_path = 'U:/Code/dev_dirs/Thailand/2023_03_14_generator_parameters_THA.xlsx'

[model]
soln_choice = '20230626_THA_Base_LowerCO2p'

[settings]
geo_cols = ['Region', 'Subregion']
validation = false
reg_ts  = true

[run]
log_file_path = 'logs/THA.log'
variables_cache = true
